# Generated by Django 3.0.8 on 2020-07-11 20:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('bname', models.CharField(max_length=150, unique=True, verbose_name='Brand Product')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cname', models.CharField(max_length=150, unique=True, verbose_name='category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ProductsWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('pwname', models.CharField(max_length=150, verbose_name='product whished by client')),
                ('indb', models.BooleanField(default=False, verbose_name='product in db')),
            ],
            options={
                'verbose_name': 'ProductsWish',
                'verbose_name_plural': 'ProductsWish',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sname', models.CharField(max_length=150, unique=True, verbose_name='Store name')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Store',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('pname', models.CharField(max_length=150, unique=True, verbose_name='product name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Barcode')),
                ('product_url', models.URLField(verbose_name='OpenFoodFact product URL')),
                ('nutriscore_score', models.SmallIntegerField(verbose_name='Score Nutriscore')),
                ('nutriscore_grade', models.CharField(max_length=1, verbose_name='Note nutriscore')),
                ('desc', models.TextField(verbose_name='Description')),
                ('photo_url', models.URLField(verbose_name='OpenFoodFact photo URL')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products_app.Brand', verbose_name='Product brand')),
                ('category', models.ManyToManyField(related_name='products', to='products_app.Category', verbose_name='Product category')),
                ('store', models.ManyToManyField(related_name='products', to='products_app.Store', verbose_name='Product store')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
