# Generated by Django 3.0.8 on 2020-07-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nb_scans',
            field=models.IntegerField(default=0, verbose_name='nombre de scans'),
        ),
    ]
