# Generated by Django 3.0.8 on 2020-07-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_nb_scans'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nb_prod',
            field=models.IntegerField(default=0, verbose_name='nbre produits'),
        ),
    ]
