# Generated by Django 3.0.8 on 2020-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_category_nb_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.CharField(choices=[('H', 'high'), ('M', 'moderate'), ('L', 'low'), ('U', 'unknown')], default='U', max_length=20, verbose_name='Lipides'),
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.CharField(choices=[('H', 'high'), ('M', 'moderate'), ('L', 'low'), ('U', 'unknown')], default='U', max_length=1, verbose_name='Sel'),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat',
            field=models.CharField(choices=[('H', 'high'), ('M', 'moderate'), ('L', 'low'), ('U', 'unknown')], default='U', max_length=20, verbose_name='Acides gras satures'),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar',
            field=models.CharField(choices=[('H', 'high'), ('M', 'moderate'), ('L', 'low'), ('U', 'unknown')], default='U', max_length=20, verbose_name='Sucres'),
        ),
    ]
