# Generated by Django 3.0.8 on 2020-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_auto_20200721_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.CharField(choices=[('H', 'HIGH'), ('M', 'MODERATE'), ('L', 'LOW'), ('U', 'UNKNOWN')], default='U', max_length=20, verbose_name='Lipides'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt',
            field=models.CharField(choices=[('H', 'HIGH'), ('M', 'MODERATE'), ('L', 'LOW'), ('U', 'UNKNOWN')], default='U', max_length=1, verbose_name='Sel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fat',
            field=models.CharField(choices=[('H', 'HIGH'), ('M', 'MODERATE'), ('L', 'LOW'), ('U', 'UNKNOWN')], default='U', max_length=20, verbose_name='Acides gras satures'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.CharField(choices=[('H', 'HIGH'), ('M', 'MODERATE'), ('L', 'LOW'), ('U', 'UNKNOWN')], default='U', max_length=20, verbose_name='Sucres'),
        ),
    ]
