# Generated by Django 3.0.8 on 2020-07-21 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products_app', '0008_auto_20200721_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='buser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pbookmarks', to='products_app.Product'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='substitute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbookmarks', to='products_app.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, through='products_app.Bookmark', to='products_app.Product'),
        ),
    ]
